# Done to increase the memory available to gradle.
org.gradle.jvmargs=-Xmx1G
org.gradle.parallel=true

# Fabric Properties
# check these on https://fabricmc.net/develop
minecraft_version=24w35a
yarn_mappings=24w35a+build.5
loader_version=0.16.3

# Mod Properties
mod_version=5.4.0-beta.1
maven_group=online.flowerinsnow.mineenter
archives_base_name=mine-enter

# Dependencies
fabric_version=0.103.1+1.21.2
modmenu_version=12.0.0-alpha.1
fabricloom_version=1.8.0-alpha.13